name: dipl
description: DIPL interview Mobile app for Android and iOS
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0

  flutter_gen: any
  flutter_screenutil: ^5.9.3
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  gap: ^3.0.1
  freezed_annotation: ^2.4.4
  dio: ^5.5.0+1
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.0
  shimmer: ^3.0.0
  riverpod_annotation: ^2.3.5
  image_picker: ^1.1.2
  jiffy: ^6.3.1
  loading_indicator: ^3.1.1
  swipe: ^0.0.1
  geolocator: ^12.0.0
dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  build_runner: 2.4.13 
  custom_lint:
  mocktail: ^1.0.0
  riverpod_generator: ^2.2.6
  riverpod_lint: ^2.0.1
  very_good_analysis: ^6.0.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
